### PR TITLE
Web feature/profile

### LINKED ISSUE #190: Create a Profile Page
**Describe the feature**
We will create a profile page that contains account information, user lists, user cart, his/her orders, and also his/her feedback that he/she has made so far. According to requirements, the user can change or update his/her account information.

**Describe solutions you've considered**
We designed a layout with a sidebar and content for this page.

### LINKED ISSUE #218: Integrate password form component
**Describe the feature**
We have a restriction for password in our requirement which is called Strong Password. Therefore, we should check for password whether it is strong or not. For the signup, password-change, and the password-reset functionalities, we should use the same password check structure.

**Describe solutions you've considered**
 Yasin Kaya wrote a password form component for that. I will use this component for the password change and password reset.

**Additional context**
Here is the requirement:
_Strong Password: A string that contains numbers or characters of length between 6 and 20. It must contain at least one lowercase letter, one uppercase letter, one numeric digit, but cannot contain white space._

### LINKED ISSUE #239: Reset password bug
**Describe the bug**
Since the backend team made some changes in the reset password endpoint, the request in the reset always gives an error. 
`400-bad-request`

**Possible code location**
It is in the `~/src/components/Login/ResetPassword.js` file. (In the post request)

**Expected behavior**
It should check the new password whether it is strong or not and then it sends a post request with the correct parameters.

**Screenshots**
image

**Additional context**
Since password check is also required, I will fix both of them together.

### PR DESCRIPTION
**Pull request by afraarslan**
Yasin Kaya and I created the user account page and added profile pages to it.

#### Changes
* When a user clicked the account button, it directs to the account page.
* Account page has a sider on the left which has a profile, order, list, cart, feedbacks, and recommendation pages.
* We did the content of the profile tab. It contains profile info, address info, and the payment info tabs.
* User can edit this profile and change his/her password from the profile info tab.
* In the addresses info page, the user can see his/her registered addresses, and a new address, and also edit or delete the registered address.
* Payment info page contains the user registered cards. The new cart can be added or a registered card can be deleted.

#### Screenshots
image

--------------

image

-------------------

image

---------

#### Notes
We also updated the reset password and forgot password requests with new endpoints.
The backend side of the payment and address functionalities are still in progress. Therefore, it will be added when the endpoints are ready.

### CODE REVIEW

File: web/carousel/src/components/PasswordForm/PasswordForm.js [hunk 1]
```diff
@@ -73,7 +83,7 @@ const PasswordForm = (props) => {
             style={passLength ? { color: "forestgreen" } : { color: "red" }}
             className={classes.PasswordCheck}
           >
-            Password should be between 6-20 characters.
+            Password should be between 6-20 letters.
```
Comment (oncelkeles) [inline web/carousel/src/components/PasswordForm/PasswordForm.js]: I think this should stay as "characters", as we count digits as well and they are not letters

File: web/carousel/src/components/UI/ConfirmPopup/ConfirmPopup.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+          <h1>{title}</h1>
+          <div className={classes.ButtonRow}>
+            <ButtonPrimary
+              onClick={() => {
+                handleConfirm();
+                onClose();
+              }}
+              title="Yes"
+            />
+            <ButtonPrimary onClick={onClose} title="No" />
```
Comment (oncelkeles) [inline web/carousel/src/components/UI/ConfirmPopup/ConfirmPopup.js]: We may use ButtonSecondary here, in order to reinforce the difference between "yes" and "no"

File: web/carousel/src/components/UI/InputUI/InputUI.js [hunk 3]
```diff
@@ -1,76 +1,95 @@
...
+        placeholder={props.placeholder}
+        style={hasIcon ? null : { paddingLeft: "0" }}
+        onClick={props.clicked}
+      />
+    </span>
+  );
+};
 
 export default InputUI;
-
```
Comment (oncelkeles) [inline web/carousel/src/components/UI/InputUI/InputUI.js:76]: Thank you dear Prettier 🥇

**Review by oncelkeles — COMMENTED** [review]
Other than one or two design issues, I think this is solid work! 💯

File: web/carousel/src/components/PasswordForm/PasswordForm.js (hunk 1 above)
Comment (afraarslan) [reply web/carousel/src/components/PasswordForm/PasswordForm.js]: Yes, you are right. I forgot to change it back.

File: web/carousel/src/components/UI/ConfirmPopup/ConfirmPopup.js (hunk 2 above)
Comment (afraarslan) [reply web/carousel/src/components/UI/ConfirmPopup/ConfirmPopup.js]: Which one is better?
image
image

Comment (oncelkeles) [reply web/carousel/src/components/UI/ConfirmPopup/ConfirmPopup.js]: Hmm, I think i was imagining the SecondaryButton with an outline with empty background. Only text looks not that good. 
I also suggest that the buttons could be "delete" and "cancel" instead of "yes" and "no". That way, we can express the button statements better in terms of UX. This is just a suggestion however.

Comment (afraarslan) [reply web/carousel/src/components/UI/ConfirmPopup/ConfirmPopup.js]: I think an outline is not necessary, but 'delete' and 'cancel' make the buttons more clear for users. I can change them.

**Review by oncelkeles — APPROVED** [review]
💯 nice work!
